[package]
name = "egg-for-lean"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[dependencies]
miniegg-with-slots = { path = "slotted/3-miniegg-with-slots" }
indexmap = "1.8.1"
libc = "0.2"